# Generated by Django 4.2 on 2023-06-04 08:09

import blog_post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='page_picture',
            field=models.ImageField(blank=True, upload_to=blog_post.models.BlogPost.post_directory_path),
        ),
    ]
