# Generated by Django 4.2 on 2023-05-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0004_alter_blogpost_options_alter_blogpost_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
    ]
